networks:
  segment_internal:
  segment_secure:

services:
  kali:
    build: 
      context: ./kali
    hostname: kali
    networks:
      segment_internal:
    ports:
      - "0:22"
    privileged: true

  jump:
    build:
      context: ./jump
      args:
        JUMP_ROOT_PASSWORD: ${JUMP_ROOT_PASSWORD}
    hostname: jump
    networks:
      segment_internal:
      segment_secure:
    expose:
      - 22

  secure:
    build:
      context: ./secure
      args:
        SECURE_FLAG: ${SECURE_FLAG}
        SECURE_ROOT_PASSWORD: ${SECURE_ROOT_PASSWORD}
    hostname: secure
    networks:
      segment_secure:
    expose:
      - 22
